---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "gitea-admin-secret.yaml"
  - "ingress.yaml"

helmCharts:
  - name: gitea
    repo: https://dl.gitea.io/charts/
    version: "8.3.0"
    releaseName: gitea
    namespace: gitea
    valuesFile: values.yaml

namespace: gitea
